# Generated by Django 4.2.2 on 2023-06-21 09:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0004_project_publisher_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('discription', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='project_publisher',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterpriseapp.category'),
        ),
        migrations.AddField(
            model_name='project_publisher',
            name='clientnamme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project_publisher',
            name='projectstartdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
