# Generated by Django 4.2.2 on 2023-06-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0005_service_publisher_project_publisher_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_publisher',
            name='Service_publisher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterpriseapp.service_publisher'),
        ),
    ]
