# Generated by Django 4.2.2 on 2023-06-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0006_project_publisher_service_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_publisher',
            name='projectstartdate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
