# Generated by Django 4.2.2 on 2023-06-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0007_alter_project_publisher_projectstartdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_publisher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
