# Generated by Django 4.2.2 on 2023-06-21 10:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0008_service_publisher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_publisher',
            name='discription',
            field=tinymce.models.HTMLField(),
        ),
    ]
