# Generated by Django 4.2.2 on 2023-06-21 11:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0009_alter_service_publisher_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_publisher',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='service_publisher',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
