# Generated by Django 4.2.2 on 2023-06-22 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0010_project_publisher_slug_service_publisher_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeserviceshow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('icon', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='service_publisher',
            name='icon',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
