# Generated by Django 4.2.2 on 2023-06-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0011_homeserviceshow_service_publisher_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ongoingproject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('village_name', models.CharField(max_length=150)),
                ('village_tall', models.CharField(max_length=150)),
                ('village_dist', models.CharField(max_length=150)),
                ('projectdetails', models.CharField(max_length=1000, null=True)),
                ('pricedetails', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
