# Generated by Django 4.2.2 on 2023-06-26 08:57

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0016_remove_emailaddress_contact_details_delete_home_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('about', models.TextField()),
                ('meta_discription', models.TextField()),
                ('copyright', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('Contact_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='enterpriseapp.contact_details')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('Contact_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_address', to='enterpriseapp.contact_details')),
            ],
        ),
    ]
