# Generated by Django 4.2.2 on 2023-06-26 11:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0017_contact_details_home_phonenumber_emailaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Topheading', models.CharField(blank=True, max_length=255, null=True)),
                ('smalltitle', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('discription', tinymce.models.HTMLField()),
            ],
        ),
    ]
