# Generated by Django 4.2.2 on 2023-06-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0018_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Aboutus',
        ),
    ]
