# Generated by Django 4.2.2 on 2023-06-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0021_aboutus_backgroundimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='service_publisher',
            name='pointitems',
            field=models.ManyToManyField(to='enterpriseapp.listitem'),
        ),
    ]
