# Generated by Django 4.2.2 on 2023-06-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0022_listitem_service_publisher_pointitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_publisher',
            name='pointitems',
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
    ]
