# Generated by Django 4.2.2 on 2023-06-26 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0023_remove_service_publisher_pointitems_delete_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_publisher',
            name='morebenifit',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_publisher',
            name='morebenifitimage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
