# Generated by Django 4.2.2 on 2023-06-27 05:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapp', '0025_service_publisher_bottomparagraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractive_location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph', tinymce.models.HTMLField()),
            ],
        ),
    ]
